package de.gym.backend;

import java.util.List;

/**
 * For easier database population with user data, this class implements the
 * methods described in the interface such as: 
 * 			get all users created by the maker.
 * 			add new user.
 * 
 * @author florina
 *
 */
public class UserDAOwithMaker implements UserDAO {

	/**
	 * Example of user data, ready to be added into the database or used for testing
	 */
	private UserMaker userMaker;
	/** List of user data, created by the maker */
	private List<User> users;

	/**
	 * Constructor creating and retrieving 20 users containing random generated data
	 * declared in the class UserMaker.
	 */
	public UserDAOwithMaker() {
		userMaker = new UserMaker(20);
		users = userMaker.getAllUsers();
	}

	/**
	 * Get all the users created by the UserMaker
	 */
	@Override
	public List<User> getAllUsers() {
		return users;
	}

	/**
	 * Add new user generated by the UserMaker
	 */
	@Override
	public void addUser(User user) {
		users.add(user);

	}

	@Override
	public String passwordEncryptionSHA(String pass) {
		// TODO Auto-generated method stub
		return null;
	}

}
